{
 "title": "CNV with ODF",
 "description": "some useful metrics for CNV and ODF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "ODF", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSD Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"rook-ceph-osd-(\\\\d+).*\"}) by (pod), \"osd_label\", \"osd-$1\", \"pod\", \"rook-ceph-osd-(\\\\d+).*\") / 1024 / 1024 / 1024",
     "legendFormat": "{{osd_label}}"
    }
   ]
  },
  {
   "title": "OSD CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"rook-ceph-osd-(\\\\d+).*\"}[1m])) by (pod), \"osd_label\", \"osd-$1\", \"pod\", \"rook-ceph-osd-(\\\\d+).*\")",
     "legendFormat": "{{osd_label}}"
    }
   ]
  },
  { "title": "CNV ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\") / 1024 / 1024 / 1024 ",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
     "legendFormat": "{{vmi}}"
    }
   ]
  }
 ]
}