{
 "title": "Descheduler with CNV",
 "description": "some useful metrics for Descheduler with CNV",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Resource Usage Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU pressure by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_cpu_waiting_seconds_total[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory pressure by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_pressure_memory_stalled_seconds_total[15m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU request by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request By node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}/1024/1024/1024) by (node) * on(node) group_left(role) kube_node_role{role=\"worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU request by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory request by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node=~\"f08-h12-000-1029u|f08-h13-000-1029u|f09-h02-000-1029u|f09-h03-000-1029u\"}/1024/1024/1024) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CNV ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "VM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(container_memory_rss{pod=~\"virt-launcher.*\"}) by (pod), \"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\") / 1024 / 1024 / 1024 ",
     "legendFormat": "{{vmi}}"
    }
   ]
  },
  {
   "title": "VM CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{pod=~\"virt-launcher.*\"}[1m])) by (pod),\"vmi\", \"$1\", \"pod\", \"virt-launcher-(.*)-[^-]+$\")",
     "legendFormat": "{{vmi}}"
    }
   ]
  }
 ]
}