{
 "title": "HyperShift API vs ETCD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "wal fsync p99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket{namespace=~\"clusters-kv.*\"}[2m])) by (namespace, pod, le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Plane Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"clusters-kv.*\", container!=\"POD\", pod!~\"virt-launcher.*\"}/1024/1024/1024) by (namespace)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "disk backend commit p99 ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_backend_commit_duration_seconds_bucket{namespace=~\"clusters-kv.*\"}[2m])) by (namespace, pod, le)) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Plane CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"clusters-kv.*\",container!=\"POD\",name!=\"\", pod!~\"virt-launcher-kv-.*\"}[2m])*100) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Request Rate (SUM)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{namespace=~\"clusters-kv.*\"}[2m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Disk Throughput ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker004-1029p|worker005-1029p\"}[2m]) / 1024 / 1024) by (instance)",
     "legendFormat": "Read - {{instance}} "
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker004-1029p|worker005-1029p\"}[2m]) / 1024 / 1024) by (instance)",
     "legendFormat": "Write - {{instance}}"
    }
   ]
  },
  {
   "title": "ETCD DISK IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{device=\"nvme0n1\", instance=~\"worker002-1029p|worker003-1029p|worker004-1029p|worker005-1029p\"} [2m]) ) by (instance)",
     "legendFormat": "Read - {{instance}}"
    },
    {
     "expr": "sum(rate(node_disk_writes_completed_total{device=\"nvme0n1\",instance=~\"worker002-1029p|worker003-1029p|worker004-1029p|worker005-1029p\"}[2m])) by (instance)",
     "legendFormat": "Write - {{instance}}"
    }
   ]
  }
 ]
}