{
 "title": "OpenShift Virtualization Performance",
 "description": "OCP Virt related performance metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "OpenShift Virtualization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "HCO System Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hco_system_health_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HCO Operator Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hyperconverged_operator_health_status",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kubevirt_number_of_vms)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Request Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster:vmi_request_cpu_cores:sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM RAM Request Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vm_resource_requests)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Pod Memory Usage/Request Delta ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_memory_delta_from_requested_bytes) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virt API Pod Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kubevirt_virt_api_up", "legendFormat": "__auto" }
   ]
  }
 ]
}